fix build failure (#17869)
[MKTARGET] pdsa_hals_test_mockapi.gtest
/bin/ld:
/sw/nic/build/x86_64/apulu/out/pdsa_hals_test_mockapi_gtest/metaswitch/stubs/test/hals/main.o:
undefined reference to symbol '_ZN3sdk3lib4slab4freeEPv'
/sw/nic/build/x86_64/apulu/lib/libslab.so: error adding symbols: DSO
missing from command line
collect2: error: ld returned 1 exit status
make: ***
[/sw/nic/build/x86_64/apulu/out/pdsa_hals_test_mockapi_gtest/pdsa_hals_test_mockapi.gtest]
Error 1
make: *** Waiting for unfinished jobs....