ionic_rdma: Support for Linux 5.1 (#12992)
* ionic: Fix up for eth driver build with Linux 5.1

* ionic_rdma: Fix up ib_register_device() for Linux 5.1

* ionic_rdma: Fix up ib_alloc_device() for Linux 5.1

* ionic_rdma: Fix up pd and ucontext code for Linux 5.1

* ionic_rdma: Fix up ib_umem_get() calls for Linux 5.1

* rdma: Update build docker to 0.7 to include kernel 5.1.8 headers

* ionic_rdma: Hook up the driver_id field for Linux 4.17+

For some reason, ioctl-based commands don't work right
without it. It's supposed to be optional.

* rdma: Enable krping on all kernels

Except OFA. That's a whole different mess.

Add it to the build docker test, too.

* rdma: Minor update to perftest

* rdma: Rename setup_apt.sh to setup_libs.sh; remove setup_yum.sh

setup_libs.sh supports yum and apt.
setup_yum.sh was obsolete.

* ionic: Fix up kcompat.h for Ubuntu pre-release kernels

To avoid this:
./include/generated/utsrelease.h:2:32: error: invalid digit "9" in octal constant
 #define UTS_UBUNTU_RELEASE_ABI 050109

None of the Ubuntu compatibility #defines are used in ionic.